In [97]:
import pandas as pd

In [98]:
df0 = pd.read_csv(r"C:\Users\Bisbii\Desktop\lipids\ngaditana\model_reaction_model_reaction_labels_before_standardization.csv")
df0.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label,idreaction_label,equation,isGeneric,isNonEnzymatic,isSpontaneous,name,source
0,22904,NaN,0,-999999.0,NaN,999999.0,48,259,259,"(9Z,12Z,15Z)-Octadecatrienoic acid + Oxygen <=...",0,0,0,R09810,KEGG
1,22905,NaN,0,-999999.0,NaN,999999.0,48,9281,9281,Pelargonidin 3-O-glucoside + 1-O-Sinapoyl-beta...,0,0,0,R10298,KEGG
2,22906,NaN,0,-999999.0,NaN,999999.0,48,261,261,"Linoleate + Oxygen <=> (8E,10R,12Z)-10-Hydrope...",0,0,0,R09811,KEGG
3,22907,NaN,0,0.0,NaN,999999.0,48,139,139,Deoxycytidine + H2O => Deoxyuridine + Ammonia,0,0,0,R02485,KEGG
4,22908,NaN,0,-999999.0,NaN,999999.0,48,2539,2539,5'-Deoxy-5-fluorocytidine + H2O <=> 5'-Deoxy-5...,0,0,0,R08221,KEGG

In [99]:
df = df.loc[(df.name.str.startswith("BMGR")) | (df.name.str.startswith("R_BMGR"))]

In [100]:
# get rows whose name ends with "_V1" or "_V2 , etc
with_version = df.loc[df.name.str.contains(r"_V\d+$")]
with_version.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label,idreaction_label,equation,isGeneric,isNonEnzymatic,isSpontaneous,name,source
20730,53017,NaN,1,0.0,NaN,1000.0,47,27856,27856,"1-(5Z,8Z,11Z,14Z,17Z-eicosapentaenoyl)-sn-glyc...",0,0,0,BMGR6162_V2,MANUAL
20731,53018,NaN,1,0.0,NaN,1000.0,47,27858,27858,"1-(5Z,8Z,11Z,14Z,17Z-eicosapentaenoyl)-2-(9Z-h...",0,0,0,BMGR0604_V1,MANUAL
20732,53019,NaN,1,0.0,NaN,1000.0,47,27859,27859,"CDP-1-(5Z,8Z,11Z,14Z,17Z-eicosapentaenoyl)-2-(...",0,0,0,BMGR0524_V1,MANUAL
20733,53020,NaN,1,0.0,NaN,1000.0,47,27860,27860,"1-(5Z,8Z,11Z,14Z,17Z-eicosapentaenoyl)-2-(9Z-h...",0,0,0,BMGR3362_V1,MANUAL
20736,53023,NaN,1,0.0,NaN,1000.0,47,27863,27863,"(5Z,8Z,11Z,14Z,17Z)-Icosapentaenoyl-CoA + 1-(5...",0,0,0,BMGR6162_V3,MANUAL

In [101]:
# update name to remove version number and add the max number + 1
as_list = with_version.name.tolist()
max_number = df.name.replace("R_BMGR", "").replace("BMGR", "").str.extract(r'(\d+)').astype(int).max().values[0]

for i in range(len(as_list)):
    as_list[i] = "BMGR" + str(max_number + 1)
    max_number += 1

In [102]:
as_list

['BMGR6240',
 'BMGR6241',
 'BMGR6242',
 'BMGR6243',
 'BMGR6244',
 'BMGR6245',
 'BMGR6246',
 'BMGR6247',
 'BMGR6248',
 'BMGR6249',
 'BMGR6250',
 'BMGR6251',
 'BMGR6252',
 'BMGR6253',
 'BMGR6254',
 'BMGR6255',
 'BMGR6256',
 'BMGR6257',
 'BMGR6258',
 'BMGR6259',
 'BMGR6260',
 'BMGR6261',
 'BMGR6262',
 'BMGR6263',
 'BMGR6264',
 'BMGR6265',
 'BMGR6266',
 'BMGR6267',
 'BMGR6268',
 'BMGR6269',
 'BMGR6270',
 'BMGR6271',
 'BMGR6272',
 'BMGR6273',
 'BMGR6274',
 'BMGR6275',
 'BMGR6276',
 'BMGR6277',
 'BMGR6278',
 'BMGR6279',
 'BMGR6280',
 'BMGR6281',
 'BMGR6282',
 'BMGR6283',
 'BMGR6284',
 'BMGR6285',
 'BMGR6286',
 'BMGR6287',
 'BMGR6288',
 'BMGR6289',
 'BMGR6290',
 'BMGR6291',
 'BMGR6292',
 'BMGR6293',
 'BMGR6294',
 'BMGR6295',
 'BMGR6296',
 'BMGR6297',
 'BMGR6298',
 'BMGR6299',
 'BMGR6300',
 'BMGR6301',
 'BMGR6302',
 'BMGR6303',
 'BMGR6304',
 'BMGR6305',
 'BMGR6306',
 'BMGR6307',
 'BMGR6308',
 'BMGR6309',
 'BMGR6310',
 'BMGR6311',
 'BMGR6312',
 'BMGR6313',
 'BMGR6314',
 'BMGR6315',
 'BMGR6316',
 'BMGR6317',
 'BMGR6318',
 'BMGR6319',
 'BMGR6320',
 'BMGR6321',
 'BMGR6322',
 'BMGR6323',
 'BMGR6324',
 'BMGR6325',
 'BMGR6326',
 'BMGR6327',
 'BMGR6328',
 'BMGR6329',
 'BMGR6330',
 'BMGR6331',
 'BMGR6332',
 'BMGR6333',
 'BMGR6334',
 'BMGR6335',
 'BMGR6336',
 'BMGR6337',
 'BMGR6338',
 'BMGR6339',
 'BMGR6340',
 'BMGR6341',
 'BMGR6342',
 'BMGR6343',
 'BMGR6344',
 'BMGR6345',
 'BMGR6346',
 'BMGR6347',
 'BMGR6348',
 'BMGR6349',
 'BMGR6350',
 'BMGR6351',
 'BMGR6352',
 'BMGR6353',
 'BMGR6354',
 'BMGR6355',
 'BMGR6356',
 'BMGR6357',
 'BMGR6358',
 'BMGR6359',
 'BMGR6360',
 'BMGR6361',
 'BMGR6362',
 'BMGR6363',
 'BMGR6364',
 'BMGR6365',
 'BMGR6366',
 'BMGR6367',
 'BMGR6368',
 'BMGR6369',
 'BMGR6370',
 'BMGR6371',
 'BMGR6372',
 'BMGR6373',
 'BMGR6374',
 'BMGR6375',
 'BMGR6376',
 'BMGR6377',
 'BMGR6378',
 'BMGR6379',
 'BMGR6380',
 'BMGR6381',
 'BMGR6382',
 'BMGR6383',
 'BMGR6384',
 'BMGR6385',
 'BMGR6386',
 'BMGR6387',
 'BMGR6388',
 'BMGR6389',
 'BMGR6390',
 'BMGR6391',
 'BMGR6392',
 'BMGR6393',
 'BMGR6394',
 'BMGR6395',
 'BMGR6396',
 'BMGR6397',
 'BMGR6398',
 'BMGR6399',
 'BMGR6400',
 'BMGR6401',
 'BMGR6402',
 'BMGR6403',
 'BMGR6404',
 'BMGR6405',
 'BMGR6406',
 'BMGR6407']

In [103]:
with_version.name = as_list

C:\Users\Bisbii\AppData\Local\Temp\ipykernel_18208\2582127936.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  with_version.name = as_list

In [104]:
len(with_version.name.unique()) == len(with_version)

True

In [105]:
# remove the rows from df0 where the idreaction_label is in the with_version df
# df0 = df0.loc[~df0.idreaction_label.isin(with_version.idreaction_label)]
#concat with initial df
# with_version = pd.concat([df0, with_version])
with_version = with_version[["idreaction_label", "name"]]
# drop duplicates and keep the last
# with_version = with_version.drop_duplicates(subset="idreaction_label", keep="last")

In [107]:
# get duplicates
with_version[with_version.duplicated(subset="idreaction_label", keep=False)]

Empty DataFrame
Columns: [idreaction_label, name]
Index: []

In [108]:
with_version.tail()

       idreaction_label      name
21124             28478  BMGR6403
21159             28514  BMGR6404
21160             28515  BMGR6405
21421             28799  BMGR6406
21422             28800  BMGR6407

In [106]:
with_version.to_csv(r"C:\Users\Bisbii\Desktop\lipids\ngaditana\bmgr_reactions_std.csv", index=False)