In [18]:
from gsmmutils.model.COBRAmodel import *
from gsmmutils import DATA_PATH
import logging
logging.getLogger("cobra").setLevel(logging.CRITICAL)
import warnings
warnings.filterwarnings("ignore")
from cobra.flux_analysis import flux_variability_analysis as fva

In [19]:
original_model = read_sbml_model(r"C:\Users\Bisbii\Downloads\Rice_Lakshmanan.xml")
original_model.objective = "Straw_Biomass"
diel_model = read_sbml_model(r"C:\Users\Bisbii\Downloads\diel_rice_Lakshmanan_model.xml")
diel_model.objective = "Biomass_Total"

In [32]:
inactive = [
            "RBPC2s",
            "Coleoptile_Biomass",
            "PRISM_blue_LED",
            "PRISM_red_LED",
            "PRISM_white_LED",
            "PRISM_green_LED",
            "GDHym",
            "GDHm",
            "AGATx",
            "AGATs",
            "ICDHc",
            "GTHPs",
            "GLCNGBc",
            "GLCNGAc",
            "MDHs",
            "MDHc",
            "ASPTAm",
            "PDHam1m",
            "PDHam2m",
            "PDHe2m",
            "PDHe3m",
            "THR3DHx",
            "FDHNc",
            "SULOm",
            "ASNS1c",
            "GLYCORc",
            "TYRTAs",
            "ARGOAT1s",
            "PGI2c",
            "PGI2s",
            "GAMPTc",
            "FTHFLc",
            "CALANc",
            "FORAc",
            "SHMTs",
            "MLTHFRs",
            "METSc",
            "GAPDHys",
            "GAPDH2s",
            "MTHFDm",
            "MTHFDc",
            "FTHFCLc",
            "MTHFDym",
            "MTHFDys",
            "GLYK2s",
            "UREASEc",
            "ATSc",
            "SHSL1s",
            "SPPAs",
            "PFPc",
            "PTOXs",
            "PFKc",
            "PFKs",
            "AAs",
            "HCO3Es",
            "HCO3Em",
            "CHLASEs",
            "ALTNDAc",
            "NADOR2u",
            "AKGCITtm",
            "AKGICITtm",
            "MALICITtm",
            "MALOAAtm",
            "OAAAKGtm",
            "OAACITtm",
            "OAAICITtm",
            "5FTHFtm",
            "MLTHFtm",
            "NA1Htm",
            "PInatm",
            "5FTHFts",
            "5MTHFts",
            "G3P_LPAREN_pi_RPAREN_tsr",
            "G6PA_LPAREN_pi_RPAREN_ts",
            "G6PB_LPAREN_pi_RPAREN_ts",
            "PEPPIts",
            "PINA1ts",
            "IPADNEts",
            "TZTNts",
            "FA140CoAr",
            "FA160CoAr",
            "FA161CoAr",
            "FA180CoAr",
            "FA181CoAr",
            "FA183CoAr"
            ]
for i in inactive:
    original_model.reactions.get_by_id(i).bounds = (0, 0)
    diel_model.reactions.get_by_id(i + "_Day").bounds = (0, 0)
    diel_model.reactions.get_by_id(i + "_Night").bounds = (0, 0)

In [34]:
for reaction in original_model.reactions:
    if reaction.id.startswith("EX_") and "C" in reaction.reactants[0].formula and reaction.id != "EX_co2_LPAREN_e_RPAREN_":
        print(reaction.id)
        reaction.bounds = (0, 1000)

for reaction in diel_model.reactions:
    if reaction.id.startswith("EX_") and "C" in reaction.reactants[0].formula and reaction.id != "EX_co2_LPAREN_e_RPAREN__Day":
        print(reaction.id)
        reaction.bounds = (0, 1000)

fba_sol_non_diel = original_model.optimize()
fba_sol_diel_model = diel_model.optimize()

EX_sucr_LPAREN_e_RPAREN_
EX_fru_DASH_B_LPAREN_e_RPAREN_
EX_glc_DASH_A_LPAREN_e_RPAREN_
EX_hco3_LPAREN_e_RPAREN_
EX_asn_DASH_L_LPAREN_e_RPAREN_
EX_gln_DASH_L_LPAREN_e_RPAREN_
EX_etoh_LPAREN_e_RPAREN_
EX_ac_LPAREN_e_RPAREN_
EX_lac_DASH_L_LPAREN_e_RPAREN_
EX_ala_DASH_L_LPAREN_e_RPAREN_
EX_arg_DASH_L_LPAREN_e_RPAREN_
EX_asp_DASH_L_LPAREN_e_RPAREN_
EX_cys_DASH_L_LPAREN_e_RPAREN_
EX_glu_DASH_L_LPAREN_e_RPAREN_
EX_gly_LPAREN_e_RPAREN_
EX_his_DASH_L_LPAREN_e_RPAREN_
EX_ile_DASH_L_LPAREN_e_RPAREN_
EX_leu_DASH_L_LPAREN_e_RPAREN_
EX_lys_DASH_L_LPAREN_e_RPAREN_
EX_met_DASH_L_LPAREN_e_RPAREN_
EX_phe_DASH_L_LPAREN_e_RPAREN_
EX_pro_DASH_L_LPAREN_e_RPAREN_
EX_ser_DASH_L_LPAREN_e_RPAREN_
EX_thr_DASH_L_LPAREN_e_RPAREN_
EX_trp_DASH_L_LPAREN_e_RPAREN_
EX_tyr_DASH_L_LPAREN_e_RPAREN_
EX_val_DASH_L_LPAREN_e_RPAREN_
EX_sucr_LPAREN_e_RPAREN__Day
EX_fru_DASH_B_LPAREN_e_RPAREN__Day
EX_glc_DASH_A_LPAREN_e_RPAREN__Day
EX_hco3_LPAREN_e_RPAREN__Day
EX_asn_DASH_L_LPAREN_e_RPAREN__Day
EX_gln_DASH_L_LPAREN_e_RPAREN__Day
EX_etoh_LPAREN_e_RPAREN__Day
EX_ac_LPAREN_e_RPAREN__Day
EX_lac_DASH_L_LPAREN_e_RPAREN__Day
EX_ala_DASH_L_LPAREN_e_RPAREN__Day
EX_arg_DASH_L_LPAREN_e_RPAREN__Day
EX_asp_DASH_L_LPAREN_e_RPAREN__Day
EX_cys_DASH_L_LPAREN_e_RPAREN__Day
EX_glu_DASH_L_LPAREN_e_RPAREN__Day
EX_gly_LPAREN_e_RPAREN__Day
EX_his_DASH_L_LPAREN_e_RPAREN__Day
EX_ile_DASH_L_LPAREN_e_RPAREN__Day
EX_leu_DASH_L_LPAREN_e_RPAREN__Day
EX_lys_DASH_L_LPAREN_e_RPAREN__Day
EX_met_DASH_L_LPAREN_e_RPAREN__Day
EX_phe_DASH_L_LPAREN_e_RPAREN__Day
EX_pro_DASH_L_LPAREN_e_RPAREN__Day
EX_ser_DASH_L_LPAREN_e_RPAREN__Day
EX_thr_DASH_L_LPAREN_e_RPAREN__Day
EX_trp_DASH_L_LPAREN_e_RPAREN__Day
EX_tyr_DASH_L_LPAREN_e_RPAREN__Day
EX_val_DASH_L_LPAREN_e_RPAREN__Day
EX_co2_LPAREN_e_RPAREN__Night
EX_sucr_LPAREN_e_RPAREN__Night
EX_fru_DASH_B_LPAREN_e_RPAREN__Night
EX_glc_DASH_A_LPAREN_e_RPAREN__Night
EX_hco3_LPAREN_e_RPAREN__Night
EX_asn_DASH_L_LPAREN_e_RPAREN__Night
EX_gln_DASH_L_LPAREN_e_RPAREN__Night
EX_etoh_LPAREN_e_RPAREN__Night
EX_ac_LPAREN_e_RPAREN__Night
EX_lac_DASH_L_LPAREN_e_RPAREN__Night
EX_ala_DASH_L_LPAREN_e_RPAREN__Night
EX_arg_DASH_L_LPAREN_e_RPAREN__Night
EX_asp_DASH_L_LPAREN_e_RPAREN__Night
EX_cys_DASH_L_LPAREN_e_RPAREN__Night
EX_glu_DASH_L_LPAREN_e_RPAREN__Night
EX_gly_LPAREN_e_RPAREN__Night
EX_his_DASH_L_LPAREN_e_RPAREN__Night
EX_ile_DASH_L_LPAREN_e_RPAREN__Night
EX_leu_DASH_L_LPAREN_e_RPAREN__Night
EX_lys_DASH_L_LPAREN_e_RPAREN__Night
EX_met_DASH_L_LPAREN_e_RPAREN__Night
EX_phe_DASH_L_LPAREN_e_RPAREN__Night
EX_pro_DASH_L_LPAREN_e_RPAREN__Night
EX_ser_DASH_L_LPAREN_e_RPAREN__Night
EX_thr_DASH_L_LPAREN_e_RPAREN__Night
EX_trp_DASH_L_LPAREN_e_RPAREN__Night
EX_tyr_DASH_L_LPAREN_e_RPAREN__Night
EX_val_DASH_L_LPAREN_e_RPAREN__Night

In [22]:
original_model.summary(fba_sol_non_diel)

In [35]:
diel_model.summary(fba_sol_diel_model)

In [36]:
data_quantum_assimilation = {
    'Quantum Yield': [fba_sol_non_diel["RBPCs"] / - fba_sol_non_diel["EX_photonVis_LPAREN_e_RPAREN_"],
                      fba_sol_diel_model["RBPCs_Day"] / - fba_sol_diel_model["EX_photonVis_LPAREN_e_RPAREN__Day"]],

    'Assimilation Quotient': [fba_sol_non_diel["RBPCs"] / fba_sol_non_diel["PSIINC"],
                              fba_sol_diel_model["RBPCs_Day"] / fba_sol_diel_model["PSIINC_Day"]]}
data_quantum_assimilationfu

{'Quantum Yield': [0.15323203453127, 0.18695911454125552],
 'Assimilation Quotient': [13.417583304578388, 16.370855491027186]}